port: 7880
rtc:
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: false

redis:
  address: samwise-redis:6379

keys:
  API_KEY: devkey
  API_SECRET: secret

logging:
  level: info
  sample: false
